<?php
/**
 * Created by PhpStorm.
 * User: adm
 * Date: 13/08/2018
 * Time: 17:53
 */

namespace App\Form;


use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;

class AgenceUpdateType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        //parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
        $builder->add('label', TextType::class, ['attr' => ['class' => 'form-control', 'placeholder' => 'ville de l\' agence']])
                ->add('submit', SubmitType::class, ['label' => 'Enregistrer', 'attr' => ['class' => 'btn btn-primary']])
        ;
    }
}