<?php
/**
 * Created by PhpStorm.
 * User: adm
 * Date: 20/08/2018
 * Time: 20:32
 */

namespace App\Form;


use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\RepeatedType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;

class PasswordChangeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        //parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
        $builder->add('password', RepeatedType::class, [ 'type' => PasswordType::class, 'invalid_message' => 'Les mots de passe ne concorde pas', 'required' => true, 'first_options' => ['attr' =>['class' => 'form-control','placeholder' => 'Votre mot de passe']], 'second_options' => ['attr' =>['class' => 'form-control','placeholder' => 'Confirmer votre mot de passe']] ])
                ->add('submit', SubmitType::class, ['label' => 'Modifier votre mot de passe', 'attr' => ['class' => 'btn btn-primary btn-lg btn-block']]);

        //$builder->addEventListener(FormEvents::PRE_SET_DATA, function (FormEvent $event) {});

    }
}