<?php
/**
 * Created by PhpStorm.
 * User: adm
 * Date: 12/08/2018
 * Time: 22:00
 */

namespace App\Form;


use App\Entity\Agence;
use App\Entity\DispoVehicule;
use App\Entity\Marque;
use App\Entity\TypeVehicule;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;

class VehiculeUpdateType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        //parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
        $builder->add('typeVehicule', EntityType::class, ['class' => TypeVehicule::class, 'choice_label' => 'label', 'attr' => ['class' => 'form-control custom-select']])
            ->add('dispoVehicule', EntityType::class, ['class' => DispoVehicule::class, 'choice_label' => 'label', 'attr' => ['class' => 'form-control custom-select']])
            ->add('agence', EntityType::class, ['class' => Agence::class, 'choice_label' => 'label', 'attr' => ['class' => 'form-control custom-select']])
            ->add('marque', EntityType::class, ['class' => Marque::class, 'choice_label' => 'label', 'attr' => ['class' => 'form-control custom-select']])
            ->add('modele', TextType::class, ['attr' => ['class' => 'form-control', 'placeholder' => 'Modèle']])
            ->add('description', TextareaType::class, ['attr' => ['class' => 'form-control', 'placeholder' => 'Entrez une description']])
            ->add('numSerie', TextType::class, ['attr' => ['class' => 'form-control' , 'placeholder' => 'Numéro de serie']])
            ->add('couleur', TextType::class, ['attr' => ['class' => 'form-control' , 'placeholder' => 'Couleur']])
            ->add('plaqueImma', TextType::class, ['attr' => ['class' => 'form-control', 'placeholder' => 'N° plaque d\'immatriculation']])
            ->add('nbKm', IntegerType::class, ['attr' => ['class' => 'form-control' , 'placeholder' => 'Kilométrage']])
            ->add('dateAchat', DateType::class, ['attr'=> ['class' => 'form-control', 'placeholder' => 'DD/MM/YYYY'], 'widget' => 'single_text', 'format' =>  'dd/MM/yyyy'])
            ->add('prixAchat', IntegerType::class, ['attr' => ['class' => 'form-control' , 'placeholder' => 'Prix d\'achat']])
            //->add('image', TextType::class, ['attr' => ['class' => 'form-control', 'placeholder' => 'Lien de l\'image']])
            ->add('image', ImageType::class)
            ->add('submit', SubmitType::class, ['attr' => ['class' => 'btn btn-primary'], 'label' => 'Modifier'])
        ;
    }
}